/* Schedule App V0.2 editable-rules patch. Keeps V0.1 storage and scheduling logic. */
(function(){
const css=`
.coverage-day-head,.priority-card-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:6px}.coverage-day-head h3{margin:0}.coverage-day-head button,.priority-card-head button,.rule-edit-btn{padding:6px 9px;font-size:.76rem}.coverage-row.editable-rule{grid-template-columns:1.5fr .7fr .7fr .7fr auto;align-items:center}.rule-actions{display:flex;justify-content:flex-end;margin-top:12px}.hours-editor{display:grid;gap:8px}.hours-editor-row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;align-items:end;padding:8px 0;border-bottom:1px solid #eef2f7}.hours-editor-row:last-child{border-bottom:0}.hours-editor-row label{font-size:.75rem}.hours-editor-row input{padding:8px 9px}.day-checks{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.priority-editor-row{display:grid;grid-template-columns:1fr minmax(130px,180px);gap:10px;align-items:center;padding:7px 0;border-bottom:1px solid #eef2f7}.priority-editor-row:last-child{border-bottom:0}.priority-editor-row span{font-weight:800}.priority-editor-row select{padding:8px 9px}@media(max-width:900px){.coverage-row.editable-rule{grid-template-columns:1.35fr .75fr .75fr auto}.coverage-row.editable-rule .coverage-required{display:none}}@media(max-width:520px){.section-title-row{align-items:center}.section-title-row>button{flex:0 0 auto}.hours-editor-row{grid-template-columns:1fr 1fr 1fr;gap:6px}.hours-editor-row strong{font-size:.82rem}.hours-editor-row label{font-size:.68rem}.hours-editor-row input{padding:7px 5px;font-size:.82rem}.coverage-row.editable-rule{grid-template-columns:1.4fr .78fr .78fr auto;gap:6px}.coverage-row.editable-rule .rule-edit-btn{padding:6px 7px}.day-checks{grid-template-columns:1fr 1fr}}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

const oldNormalize=normalizeState;
normalizeState=function(){oldNormalize();state.meta ||= {schemaVersion:1};state.meta.appVersion='0.2.0';};
const oldEmpty=emptyState;
emptyState=function(){const s=oldEmpty();s.meta.appVersion='0.2.0';return s;};
const oldBind=bindActions;
bindActions=function(){oldBind();
  $('addCoverageBtn')?.addEventListener('click',()=>openCoverageDialog());
  $('closeCoverageDialog')?.addEventListener('click',()=>$('coverageDialog').close());
  $('coverageForm')?.addEventListener('submit',saveCoverageRule);
  $('deleteCoverageBtn')?.addEventListener('click',deleteCoverageRule);
  $('coverageToClose')?.addEventListener('change',syncCoverageEndControl);
  $('addPriorityBtn')?.addEventListener('click',()=>openPriorityDialog());
  $('closePriorityDialog')?.addEventListener('click',()=>$('priorityDialog').close());
  $('priorityForm')?.addEventListener('submit',savePriorityRule);
  $('deletePriorityBtn')?.addEventListener('click',deletePriorityRule);
  $('priorityRole')?.addEventListener('change',()=>renderPriorityEmployeeEditor());
};
const oldRenderAll=renderAll;
renderAll=function(){oldRenderAll();renderBusinessHoursRules();};

window.renderBusinessHoursRules=function(){
  const root=$('businessHoursRules');if(!root||!state)return;root.innerHTML='';
  const grid=document.createElement('div');grid.className='hours-editor';
  DAYS.forEach(day=>{const h=state.businessHours[day]||{open:'11:00',close:'20:00'};const row=document.createElement('div');row.className='hours-editor-row';row.innerHTML=`<strong>${DAY_LABEL[day]}</strong><label>Open<input type="time" data-hours-day="${day}" data-hours-field="open" value="${h.open||''}"></label><label>Close<input type="time" data-hours-day="${day}" data-hours-field="close" value="${h.close||''}"></label>`;grid.appendChild(row);});
  const actions=document.createElement('div');actions.className='rule-actions';const save=document.createElement('button');save.type='button';save.className='primary';save.textContent='Save Business Hours';save.onclick=()=>{qsa('[data-hours-day]',root).forEach(i=>{state.businessHours[i.dataset.hoursDay] ||= {};state.businessHours[i.dataset.hoursDay][i.dataset.hoursField]=i.value;});saveState();showToast('Business hours saved — regenerate schedule to apply');};actions.appendChild(save);root.append(grid,actions);
};

window.renderCoverageRules=function(){
  const root=$('coverageRules');if(!root||!state)return;root.innerHTML='';
  DAYS.forEach(day=>{const box=document.createElement('div');box.className='coverage-day';const head=document.createElement('div');head.className='coverage-day-head';head.innerHTML=`<h3>${DAY_LABEL[day]}</h3>`;const add=document.createElement('button');add.type='button';add.textContent='Add';add.onclick=()=>openCoverageDialog(day);head.appendChild(add);box.appendChild(head);const rules=state.coverageTemplates[day]||[];if(!rules.length){const p=document.createElement('p');p.className='small';p.textContent='No normal coverage rules.';box.appendChild(p);}rules.forEach(r=>{const row=document.createElement('div');row.className='coverage-row editable-rule';row.innerHTML=`<div><strong>${escapeHtml(r.label)}</strong><br><span class="list-row-sub">${roleLabel(r.role)}</span></div><div>${fmtTime(r.start)}</div><div>${r.end==='CLOSE'?'Close':fmtTime(r.end)}</div><div class="coverage-required">${r.required?'Required':'Optional'}</div>`;const edit=document.createElement('button');edit.type='button';edit.className='rule-edit-btn';edit.textContent='Edit';edit.onclick=()=>openCoverageDialog(day,r.id);row.appendChild(edit);box.appendChild(row);});root.appendChild(box);});
};

window.openCoverageDialog=function(day='monday',ruleId=''){
  const rule=(state.coverageTemplates[day]||[]).find(r=>r.id===ruleId)||null;$('coverageDialogTitle').textContent=rule?'Edit Coverage':'Add Coverage';$('coverageId').value=rule?.id||'';$('coverageDay').innerHTML=DAYS.map(d=>`<option value="${d}">${DAY_LABEL[d]}</option>`).join('');$('coverageDay').value=day;$('coverageLabel').value=rule?.label||'';$('coverageRole').value=rule?.role||'server';$('coverageStart').value=rule?.start||state.businessHours[day]?.open||'11:00';$('coverageToClose').checked=rule?.end==='CLOSE';$('coverageEnd').value=rule&&rule.end!=='CLOSE'?rule.end:'15:30';$('coverageRequired').checked=rule?rule.required!==false:true;$('deleteCoverageBtn').classList.toggle('hidden',!rule);syncCoverageEndControl();$('coverageDialog').showModal();
};
window.syncCoverageEndControl=function(){const c=$('coverageToClose').checked;$('coverageEnd').disabled=c;$('coverageEnd').required=!c;};
window.saveCoverageRule=function(e){e.preventDefault();const day=$('coverageDay').value,id=$('coverageId').value||uid('coverage'),end=$('coverageToClose').checked?'CLOSE':$('coverageEnd').value;if(!$('coverageStart').value||!end)return;let old=null;DAYS.forEach(d=>{if((state.coverageTemplates[d]||[]).some(r=>r.id===id))old=d;});if(old&&old!==day)state.coverageTemplates[old]=state.coverageTemplates[old].filter(r=>r.id!==id);state.coverageTemplates[day] ||= [];const r={id,label:$('coverageLabel').value.trim(),role:$('coverageRole').value,start:$('coverageStart').value,end,required:$('coverageRequired').checked};const i=state.coverageTemplates[day].findIndex(x=>x.id===id);if(i>=0)state.coverageTemplates[day][i]=r;else state.coverageTemplates[day].push(r);state.coverageTemplates[day].sort((a,b)=>minutes(a.start)-minutes(b.start));saveState();renderCoverageRules();$('coverageDialog').close();showToast('Coverage rule saved — regenerate schedule to apply');};
window.deleteCoverageRule=function(){const id=$('coverageId').value;if(!id||!confirm('Delete this coverage rule?'))return;DAYS.forEach(d=>state.coverageTemplates[d]=(state.coverageTemplates[d]||[]).filter(r=>r.id!==id));saveState();renderCoverageRules();$('coverageDialog').close();showToast('Coverage rule deleted');};

window.renderPriorityRules=function(){
  const root=$('priorityRules');if(!root||!state)return;root.innerHTML='';const rules=state.priorityRules||[];if(!rules.length){root.innerHTML='<p>No priority rules yet.</p>';return;}rules.forEach(rule=>{const card=document.createElement('div');card.className='priority-card';const head=document.createElement('div');head.className='priority-card-head';const desc=document.createElement('div');desc.innerHTML=`<strong>${escapeHtml(rule.label)}</strong><div class="list-row-sub">${roleLabel(rule.role)} · ${(rule.days||[]).map(d=>DAY_LABEL[d]).join(', ')}${rule.startBefore?` · starts before ${fmtTime(rule.startBefore)}`:''}</div>`;const edit=document.createElement('button');edit.type='button';edit.textContent='Edit';edit.onclick=()=>openPriorityDialog(rule.id);head.append(desc,edit);card.appendChild(head);(rule.tiers||[]).forEach((tier,ti)=>{const line=document.createElement('div');line.className='priority-tier';const lab=document.createElement('span');lab.className='tier-label';lab.textContent=`Tier ${ti+1}`;line.appendChild(lab);tier.forEach(empId=>{const emp=employeeById(empId);if(!emp)return;const chip=document.createElement('span');chip.className='priority-person';chip.append(document.createTextNode(emp.name));const up=document.createElement('button'),down=document.createElement('button');up.type=down.type='button';up.textContent='▲';down.textContent='▼';up.disabled=ti===0;down.disabled=ti===rule.tiers.length-1;up.onclick=()=>movePriority(rule.id,empId,ti,ti-1);down.onclick=()=>movePriority(rule.id,empId,ti,ti+1);chip.append(up,down);line.appendChild(chip);});card.appendChild(line);});root.appendChild(card);});
};
window.buildPriorityDays=function(selected=[]){const root=$('priorityDays');root.innerHTML='';DAYS.forEach(day=>{const lab=document.createElement('label');lab.className='checkline';lab.innerHTML=`<input type="checkbox" data-priority-day="${day}" ${selected.includes(day)?'checked':''}><span>${DAY_LABEL[day]}</span>`;root.appendChild(lab);});};
window.openPriorityDialog=function(ruleId=''){const rule=(state.priorityRules||[]).find(r=>r.id===ruleId)||null;$('priorityDialogTitle').textContent=rule?'Edit Priority Rule':'Add Priority Rule';$('priorityId').value=rule?.id||'';$('priorityLabel').value=rule?.label||'';$('priorityRole').value=rule?.role||'server';$('priorityStartBefore').value=rule?.startBefore||'';buildPriorityDays(rule?.days||[]);$('deletePriorityBtn').classList.toggle('hidden',!rule);renderPriorityEmployeeEditor(rule);$('priorityDialog').showModal();};
window.renderPriorityEmployeeEditor=function(rule=null){const root=$('priorityEmployeeEditor');if(!root)return;const role=$('priorityRole').value,id=$('priorityId').value;if(!rule&&id)rule=(state.priorityRules||[]).find(r=>r.id===id)||null;const map={};(rule?.tiers||[]).forEach((tier,i)=>tier.forEach(empId=>map[empId]=i+1));root.innerHTML='';const list=state.employees.filter(e=>e.active&&e.roles?.includes(role)).sort((a,b)=>a.name.localeCompare(b.name));if(!list.length){root.innerHTML='<p class="small">No active employees have this role.</p>';return;}list.forEach(emp=>{const row=document.createElement('div');row.className='priority-editor-row';row.innerHTML=`<span>${escapeHtml(emp.name)}</span><select data-priority-employee="${emp.id}"><option value="0">Not in rule</option><option value="1">Tier 1</option><option value="2">Tier 2</option><option value="3">Tier 3</option><option value="4">Tier 4</option></select>`;row.querySelector('select').value=String(map[emp.id]||0);root.appendChild(row);});};
window.savePriorityRule=function(e){e.preventDefault();const days=qsa('[data-priority-day]:checked',$('priorityDays')).map(x=>x.dataset.priorityDay);if(!days.length)return alert('Choose at least one day.');const tiers=[[],[],[],[]];qsa('[data-priority-employee]',$('priorityEmployeeEditor')).forEach(s=>{const n=+s.value;if(n)tiers[n-1].push(s.dataset.priorityEmployee);});const compact=tiers.filter(t=>t.length);if(!compact.length)return alert('Assign at least one employee to a priority tier.');const id=$('priorityId').value||uid('priority'),r={id,label:$('priorityLabel').value.trim(),days,role:$('priorityRole').value,startBefore:$('priorityStartBefore').value||null,tiers:compact};state.priorityRules ||= [];const i=state.priorityRules.findIndex(x=>x.id===id);if(i>=0)state.priorityRules[i]=r;else state.priorityRules.push(r);saveState();renderPriorityRules();$('priorityDialog').close();showToast('Priority rule saved — regenerate schedule to apply');};
window.deletePriorityRule=function(){const id=$('priorityId').value;if(!id||!confirm('Delete this priority rule?'))return;state.priorityRules=(state.priorityRules||[]).filter(r=>r.id!==id);saveState();renderPriorityRules();$('priorityDialog').close();showToast('Priority rule deleted');};
})();
